#!/usr/bin/env python

import argparse
import shutil
import socket
import subprocess

from http.server import BaseHTTPRequestHandler, HTTPServer


PAGE = b"""\
<!doctype html>
<html>
<head>
  <meta name="viewport"
        content="width=device-width, initial-scale=1,
                 maximum-scale=1, user-scalable=no">
  <style>
    html, body {
      width: 100%;
      height: 100%;
      overflow: hidden;
      background: #000;
    }
    body {
      display: flex;
      align-items: center;
      justify-content: center;
    }
    #indicator {
      width: 120px;
      height: 120px;
      border-radius: 50%;
      background: red;
      border: 3px solid yellow;
    }
    #indicator.enabled {
      background: green;
    }
  </style>
</head>
<body>
  <div id="indicator"></div>
  <script>
    const indicator = document.getElementById('indicator');
    document.addEventListener('touchstart', e => {
      e.preventDefault();
      indicator.classList.toggle('enabled');
      fetch(location.href, { method: 'POST' });
    }, { passive: false });
  </script>
</body>
</html>
"""


class RequestHandler(BaseHTTPRequestHandler):
    state = False
    enable: list[str]
    disable: list[str]

    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "text/html")
        self.end_headers()
        self.wfile.write(PAGE)

    def do_POST(self):
        type(self).state = not type(self).state
        subprocess.run(
            type(self).enable if type(self).state else type(self).disable,
            check=False
        )
        self.send_response(204)
        self.end_headers()

    def log_message(self, format, *args):
        pass


def check_amidi():
    if shutil.which("amidi") is None:
        print("amidi dependency not found")
        return False
    return True

def main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description="Use your smartphone as a MIDI footswitch",
    )
    parser.add_argument(
        "-q", "--quiet",
        action="store_true",
        help="do not print extra messages",
    )
    parser.add_argument(
        "-p", "--port",
        type=int,
        default=8080,
        help="HTTP server port",
    )
    parser.add_argument(
        "-D", "--device",
        default="hw:3,1",
        help="MIDI device name",
    )
    parser.add_argument(
        "-d", "--disable",
        default="C0 00",
        metavar="HEX",
        help="hexadecimal bytes for disable action",
    )
    parser.add_argument(
        "-e", "--enable",
        default="C0 01",
        metavar="HEX",
        help="hexadecimal bytes for enable action",
    )
    args = parser.parse_args()

    if not check_amidi():
        return 1

    RequestHandler.enable = ["amidi", "--port", args.device, "--send-hex", args.enable]
    RequestHandler.disable = ["amidi", "--port", args.device, "--send-hex", args.disable]

    server = HTTPServer(("0.0.0.0", args.port), RequestHandler)
    hostname = socket.gethostname()
    ip = socket.gethostbyname(hostname)

    if not args.quiet:
        print(f"Connect your smartphone to the same WI-FI network and open http://{ip}:{args.port}")

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        if not args.quiet:
            print("\nLet's jam again soon!")
    finally:
        server.server_close()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
