name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: "1.27.0"
      - run: |
          go get .
      - run: |
          sudo apt-get update && sudo apt-get install -y upx-ucl
      - run: |
          make build BIN=stomp-phone-${{ github.ref_name }}-linux-x64
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "stomp-phone*"
